const languages = {
  af: { name: 'Afrikaans', code: 'af-ZA' },
  sq: { name: 'Albanian', code: 'sq-AL' },
  am: { name: 'Amharic', code: 'am-ET' },
  ar: { name: 'Arabic', code: 'ar-SA' },
  hy: { name: 'Armenian', code: 'hy-AM' },
  az: { name: 'Azerbaijani', code: 'az-AZ' },
  eu: { name: 'Basque', code: 'eu-ES' },
  be: { name: 'Belarusian', code: 'be-BY' },
  bn: { name: 'Bengali', code: 'bn-BD' },
  bs: { name: 'Bosnian', code: 'bs-BA' },
  bg: { name: 'Bulgarian', code: 'bg-BG' },
  ca: { name: 'Catalan', code: 'ca-ES' },
  ceb: { name: 'Cebuano', code: 'ceb-PH' },
  zh: { name: 'Chinese (Simplified)', code: 'zh-CN' },
  'zh-TW': { name: 'Chinese (Traditional)', code: 'zh-TW' },
  co: { name: 'Corsican', code: 'co-FR' },
  hr: { name: 'Croatian', code: 'hr-HR' },
  cs: { name: 'Czech', code: 'cs-CZ' },
  da: { name: 'Danish', code: 'da-DK' },
  nl: { name: 'Dutch', code: 'nl-NL' },
  en: { name: 'English', code: 'en-US' },
  eo: { name: 'Esperanto', code: 'eo-EO' },
  et: { name: 'Estonian', code: 'et-EE' },
  fi: { name: 'Finnish', code: 'fi-FI' },
  fr: { name: 'French', code: 'fr-FR' },
  fy: { name: 'Frisian', code: 'fy-NL' },
  gl: { name: 'Galician', code: 'gl-ES' },
  ka: { name: 'Georgian', code: 'ka-GE' },
  de: { name: 'German', code: 'de-DE' },
  el: { name: 'Greek', code: 'el-GR' },
  gu: { name: 'Gujarati', code: 'gu-IN' },
  ht: { name: 'Haitian Creole', code: 'ht-HT' },
  ha: { name: 'Hausa', code: 'ha-NG' },
  haw: { name: 'Hawaiian', code: 'haw-US' },
  he: { name: 'Hebrew', code: 'he-IL' },
  hi: { name: 'Hindi', code: 'hi-IN' },
  hmn: { name: 'Hmong', code: 'hmn-CN' },
  hu: { name: 'Hungarian', code: 'hu-HU' },
  is: { name: 'Icelandic', code: 'is-IS' },
  ig: { name: 'Igbo', code: 'ig-NG' },
  id: { name: 'Indonesian', code: 'id-ID' },
  ga: { name: 'Irish', code: 'ga-IE' },
  it: { name: 'Italian', code: 'it-IT' },
  ja: { name: 'Japanese', code: 'ja-JP' },
  jv: { name: 'Javanese', code: 'jv-ID' },
  kn: { name: 'Kannada', code: 'kn-IN' },
  kk: { name: 'Kazakh', code: 'kk-KZ' },
  km: { name: 'Khmer', code: 'km-KH' },
  rw: { name: 'Kinyarwanda', code: 'rw-RW' },
  ko: { name: 'Korean', code: 'ko-KR' },
  ku: { name: 'Kurdish', code: 'ku-TR' },
  ky: { name: 'Kyrgyz', code: 'ky-KG' },
  lo: { name: 'Lao', code: 'lo-LA' },
  lv: { name: 'Latvian', code: 'lv-LV' },
  lt: { name: 'Lithuanian', code: 'lt-LT' },
  lb: { name: 'Luxembourgish', code: 'lb-LU' },
  mk: { name: 'Macedonian', code: 'mk-MK' },
  mg: { name: 'Malagasy', code: 'mg-MG' },
  ms: { name: 'Malay', code: 'ms-MY' },
  ml: { name: 'Malayalam', code: 'ml-IN' },
  mt: { name: 'Maltese', code: 'mt-MT' },
  mi: { name: 'Maori', code: 'mi-NZ' },
  mr: { name: 'Marathi', code: 'mr-IN' },
  mn: { name: 'Mongolian', code: 'mn-MN' },
  my: { name: 'Myanmar (Burmese)', code: 'my-MM' },
  ne: { name: 'Nepali', code: 'ne-NP' },
  no: { name: 'Norwegian', code: 'no-NO' },
  or: { name: 'Odia (Oriya)', code: 'or-IN' },
  ps: { name: 'Pashto', code: 'ps-AF' },
  fa: { name: 'Persian', code: 'fa-IR' },
  pl: { name: 'Polish', code: 'pl-PL' },
  pt: { name: 'Portuguese', code: 'pt-PT' },
  pa: { name: 'Punjabi', code: 'pa-IN' },
  ro: { name: 'Romanian', code: 'ro-RO' },
  ru: { name: 'Russian', code: 'ru-RU' },
  sm: { name: 'Samoan', code: 'sm-WS' },
  gd: { name: 'Scottish Gaelic', code: 'gd-GB' },
  sr: { name: 'Serbian', code: 'sr-RS' },
  st: { name: 'Sesotho', code: 'st-ZA' },
  sn: { name: 'Shona', code: 'sn-ZW' },
  sd: { name: 'Sindhi', code: 'sd-IN' },
  si: { name: 'Sinhala', code: 'si-LK' },
  sk: { name: 'Slovak', code: 'sk-SK' },
  sl: { name: 'Slovenian', code: 'sl-SI' },
  so: { name: 'Somali', code: 'so-SO' },
  es: { name: 'Spanish', code: 'es-ES' },
  su: { name: 'Sundanese', code: 'su-ID' },
  sw: { name: 'Swahili', code: 'sw-KE' },
  sv: { name: 'Swedish', code: 'sv-SE' },
  tl: { name: 'Tagalog (Filipino)', code: 'tl-PH' },
  tg: { name: 'Tajik', code: 'tg-TJ' },
  ta: { name: 'Tamil', code: 'ta-IN' },
  tt: { name: 'Tatar', code: 'tt-RU' },
  te: { name: 'Telugu', code: 'te-IN' },
  th: { name: 'Thai', code: 'th-TH' },
  tr: { name: 'Turkish', code: 'tr-TR' },
  tk: { name: 'Turkmen', code: 'tk-TM' },
  uk: { name: 'Ukrainian', code: 'uk-UA' },
  ur: { name: 'Urdu', code: 'ur-PK' },
  uz: { name: 'Uzbek', code: 'uz-UZ' },
  vi: { name: 'Vietnamese', code: 'vi-VN' },
  cy: { name: 'Welsh', code: 'cy-GB' },
  xh: { name: 'Xhosa', code: 'xh-ZA' },
  yi: { name: 'Yiddish', code: 'yi-US' },
  yo: { name: 'Yoruba', code: 'yo-NG' },
  zu: { name: 'Zulu', code: 'zu-ZA' },
};

export default languages;
